version: '3.8'

services:

    elasticsearch:
        image: elasticsearch:8.17.2
        hostname: elasticsearch
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ports:
            - "9200:9200"
        volumes:
            - "./volumes/es_data:/usr/share/elasticsearch/data"
